In [1]:
import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

2021-10-31 18:48:51.773196: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-31 18:48:51.773238: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.6.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train[:500]
y_train = y_train[:500]
x_test = x_test[:500]
y_test = y_test[:500]
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2021-10-31 18:48:53.348226: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-10-31 18:48:53.348276: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-31 18:48:53.348298: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-44-43): /proc/driver/nvidia/version does not exist
2021-10-31 18:48:53.348572: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.135,  0.104, -0.361,  0.395,  0.324, -0.572,  0.558, -0.351,
         0.13 , -0.457]], dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.9078884

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

2021-10-31 18:48:53.560122: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/5
16/16 [==============================] - 0s 2ms/step - loss: 1.9483 - accuracy: 0.3820
Epoch 2/5
16/16 [==============================] - 0s 2ms/step - loss: 1.1042 - accuracy: 0.7680
Epoch 3/5
16/16 [==============================] - 0s 2ms/step - loss: 0.6648 - accuracy: 0.8460
Epoch 4/5
16/16 [==============================] - 0s 2ms/step - loss: 0.4719 - accuracy: 0.8900
Epoch 5/5
16/16 [==============================] - 0s 2ms/step - loss: 0.3840 - accuracy: 0.9040


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

16/16 - 0s - loss: 0.6663 - accuracy: 0.7980


[0.6663129329681396, 0.7979999780654907]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.002, 0.   , 0.006, 0.005, 0.006, 0.003, 0.001, 0.912, 0.002,
        0.065],
       [0.027, 0.005, 0.801, 0.018, 0.001, 0.062, 0.078, 0.   , 0.006,
        0.001],
       [0.003, 0.888, 0.02 , 0.013, 0.006, 0.009, 0.016, 0.014, 0.023,
        0.007],
       [0.956, 0.   , 0.003, 0.   , 0.   , 0.006, 0.029, 0.005, 0.   ,
        0.   ],
       [0.01 , 0.002, 0.015, 0.007, 0.829, 0.008, 0.013, 0.046, 0.017,
        0.053]], dtype=float32)>